spring.application.name=backend

# ===============================
# DATABASE CONFIGURATION (Supabase Postgres)
# ===============================
spring.datasource.url=jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.rkoabaxzbfgwiolruken
spring.datasource.password=mYDluYThGC1kF14e
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24xMjM0NTY3ODkwMTIzNDU2Nzg5MA==
jwt.expiration=86400000